import "~/styles/globals.css";

import type{ Metadata, Viewport } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";




export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};


const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-orange-200">
        
        {/* iPhone safe area spacer */}
        <div className="h-[env(safe-area-inset-top)] w-full bg-orange-200" />

        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}

